AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*
    - spec/fixtures/**/*
    - .git/**/*
    - bin/**/*
    - config/routes
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - log/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/LineLength:
  Max: 120

# Rails:
#   Enabled: true

Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Max: 256
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 24

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'