version: "3.9"
services:
  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: ghcr.io/annaaleynik/cookbook:master
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env
    command: bin/docker-entrypoint  
  redis:
    image: "redis:alpine"
  sidekiq:
    image: ghcr.io/annaaleynik/cookbook:master
    depends_on:
      - app
    command: sh -c 'bundle exec sidekiq'
volumes:
  db-data:
